import { TagsRelationTables } from "../database/types";
import { EntitiesWithPermissionCheck } from "../types/entityTypes";

export const AllEntities = [
  "characters",
  "blueprints",
  "blueprint_instances",
  "documents",
  "maps",
  "graphs",
  "calendars",
  "dictionaries",
  "character_fields_templates",
  "character_fields",
  "conversations",
  "random_tables",
  "tags",
];

export const SubEntityEnum = [
  "alter_names",
  "blueprint_instances",
  "map_pins",
  "character_map_pins",
  "map_layers",
  "nodes",
  "edges",
  "events",
  "random_table_options",
  "random_table_suboptions",
  "words",
];

export const EntitiesWithTagsTablesEnum: TagsRelationTables[] = [
  "_charactersTotags",
  "_documentsTotags",
  "_graphsTotags",
  "_mapsTotags",
  "_calendarsTotags",
  "_dictionariesTotags",
  "_blueprint_instancesTotags",
  "_edgesTotags",
  "_nodesTotags",
];

export const EntitiesWithoutProjectIdEnum = ["map_pins", "character_map_pins", "map_layers", "nodes", "edges", "events"];

export const UserNotificationEntitiesEnum = [
  "characters",
  "blueprints",
  "blueprint_instances",
  "documents",
  "maps",
  "map_pins",
  "graphs",
  "calendars",
  "events",
  "dictionaries",
  "words",
  "character_fields_templates",
  "tags",
];

export const BulkDeleteEntitiesEnum = [
  "characters",
  "blueprints",
  "blueprint_instances",
  "documents",
  "maps",
  "graphs",
  "nodes",
  "edges",
  "calendars",
  "events",
  "dictionaries",
  "words",
  "random_tables",
  "random_table_options",
  "tags",
  "images",
];

export const RolePermissionsEnum = [
  "create_characters" as const,
  "read_characters" as const,
  "update_characters" as const,
  "delete_characters" as const,
  "create_blueprints" as const,
  "read_blueprints" as const,
  "update_blueprints" as const,
  "delete_blueprints" as const,
  "create_blueprint_instances" as const,
  "read_blueprint_instances" as const,
  "update_blueprint_instances" as const,
  "delete_blueprint_instances" as const,
  "create_documents" as const,
  "read_documents" as const,
  "update_documents" as const,
  "delete_documents" as const,
  "create_maps" as const,
  "read_maps" as const,
  "update_maps" as const,
  "delete_maps" as const,
  "create_graphs" as const,
  "read_graphs" as const,
  "update_graphs" as const,
  "delete_graphs" as const,
  "create_calendars" as const,
  "read_calendars" as const,
  "update_calendars" as const,
  "delete_calendars" as const,
  "create_dictionaries" as const,
  "read_dictionaries" as const,
  "update_dictionaries" as const,
  "delete_dictionaries" as const,
  "create_random_tables" as const,
  "read_random_tables" as const,
  "update_random_tables" as const,
  "delete_random_tables" as const,
  "create_tags" as const,
  "read_tags" as const,
  "update_tags" as const,
  "delete_tags" as const,
  "create_character_fields_templates" as const,
  "read_character_fields_templates" as const,
  "update_character_fields_templates" as const,
  "delete_character_fields_templates" as const,
  "create_assets" as const,
  "read_assets" as const,
  "update_assets" as const,
  "delete_assets" as const,
];

export const EntitiesWithPermissionsEnum: EntitiesWithPermissionCheck[] = [
  "characters",
  "blueprints",
  "blueprint_instances",
  "documents",
  "maps",
  "graphs",
  "calendars",
  "dictionaries",
  "random_tables",
  "images",
  "tags",
  "character_fields_templates",
];
